### ISSUE TITLE
Bug Fix

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/ResearchPaperPublisher#2]
Home Page -> Go on Category [Activated] -> Check navbar you will find no categories in drop down.
The issue needed to be fixed in navigation category drop down should always be working.

**Comment by vinay4563** [comment]
Could you specify the folder in which the change is to be done ?

**Comment by lucifer1708** [comment]
assign me !!!!

**Comment by Deepak91168** [comment]
Any Updates Anyone!

**Comment by vinay4563** [comment]
@Deepak91168  Can you specify the folder in which change is to be done?

**Comment by lucifer1708** [comment]
> Any Updates Anyone!

It is solved in my other PR, with commit c63f101b728d306a4ad07e7c3ccf0c8c0f7fec71
