### ISSUE TITLE
Fix Images inside cards!

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/ResearchPaperPublisher#25]
![Screenshot from 2023-07-27 10-24-21](https://github.com/Deepak91168/ResearchPaperPublisher/assets/78257493/5ec0c2dc-849e-4c05-a4d6-6ec1173d2054)
As it can be seen clearly! images are stretching and it is required to be fixed!

**Comment by Duesenberg** [comment]
Hello, can I give this a shot?

**Comment by aparna-u** [comment]
<img width="1018" alt="image" src="https://github.com/Deepak91168/ResearchPaperPublisher/assets/36874105/87d0f3fa-a530-42a6-90c5-89fa30437d83">

**Comment by Deepak91168** [comment]
@Duesenberg 
The issue is resolved by @aparna-u 
You can check [similar issue](https://github.com/Deepak91168/ResearchPaperPublisher/issues/27) :)
