### ISSUE TITLE
Fix this extra spacing

### ISSUE THREAD

**Issue by Deepak91168** [Deepak91168/ResearchPaperPublisher#4]
- Go to post and you will find extra space 
- Make it dynamic borders should adjust according to content

![Screenshot from 2022-10-20 21-30-27](https://user-images.githubusercontent.com/78257493/196999752-d2b7872e-917a-4def-b9c4-c138efe4271c.png)

**Comment by rohitsinghind** [comment]
hey, can u assign this to me

**Comment by harsh0620** [comment]
Hi @Deepak91168 Please assign me this task.

**Comment by kashish0604** [comment]
hey @Deepak91168 can you assign this issue to me i can work on it

**Comment by Deepak91168** [comment]
Any updates anyone !
